In [1]:
import pandas as pd

In [4]:
dict1 ={'Name':['Priyang','Aadhya','Krisha','Vedant','Parshv',
                'Mittal','Archana'],
                'Marks':[98,89,99,87,90,83,99],
                'Gender':['Male','Female','Female','Male','Male',
                         'Female','Female']
               }
df1=pd.DataFrame(dict1)
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [5]:
df1.head(3)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female

In [6]:
df1.tail(3)

      Name  Marks  Gender
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [9]:
print('Number of Rows', df1.shape[0])
print('Number of Column', df1.shape[1])

Number of Rows 7
Number of Column 3

In [10]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      str
dtypes: int64(1), str(2)
memory usage: 300.0 bytes

In [14]:
df1.isnull().sum()

Name      0
Marks     0
Gender    0
dtype: int64

In [16]:
df1.describe(include ='all')

           Name      Marks  Gender
count         7   7.000000       7
unique        7        NaN       2
top     Priyang        NaN  Female
freq          1        NaN       4
mean        NaN  92.142857     NaN
std         NaN   6.491753     NaN
min         NaN  83.000000     NaN
25%         NaN  88.000000     NaN
50%         NaN  90.000000     NaN
75%         NaN  98.500000     NaN
max         NaN  99.000000     NaN

In [17]:
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [20]:
df1['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [21]:
df1['Gender'].nunique()

2

In [22]:
df1['Gender'].value_counts()

Gender
Female    4
Male      3
Name: count, dtype: int64

In [32]:
df1[df1['Marks']>=90]

      Name  Marks  Gender
0  Priyang     98    Male
2   Krisha     99  Female
4   Parshv     90    Male
6  Archana     99  Female

In [33]:
len(df1[(df1['Marks']>=90) & (df1['Marks']<=100)])

4

In [34]:
sum(df1['Marks'].between(90,100))

4

In [35]:
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [36]:
df1['Marks'].mean()

np.float64(92.14285714285714)

In [58]:
def marks(x):
    return x/2

df1['Half marks']=df1['Marks'].apply(marks)
df1

      Name  Marks  Gender  Male_Female  Half marks
0  Priyang     98    Male            1        49.0
1   Aadhya     89  Female            0        44.5
2   Krisha     99  Female            0        49.5
3   Vedant     87    Male            1        43.5
4   Parshv     90    Male            1        45.0
5   Mittal     83  Female            0        41.5
6  Archana     99  Female            0        49.5

In [44]:
df1['Marks'].apply(lambda x: x/2)

0    49.0
1    44.5
2    49.5
3    43.5
4    45.0
5    41.5
6    49.5
Name: Marks, dtype: float64

In [45]:
df1['Name'].apply(len)

0    7
1    6
2    6
3    6
4    6
5    6
6    7
Name: Name, dtype: int64

In [46]:
df1

      Name  Marks  Gender  Half marks
0  Priyang     98    Male        49.0
1   Aadhya     89  Female        44.5
2   Krisha     99  Female        49.5
3   Vedant     87    Male        43.5
4   Parshv     90    Male        45.0
5   Mittal     83  Female        41.5
6  Archana     99  Female        49.5

In [57]:
df1['Male_Female']=df1['Gender'].map({'Male':1 , 'Female': 0})
df1

      Name  Marks  Gender  Male_Female
0  Priyang     98    Male            1
1   Aadhya     89  Female            0
2   Krisha     99  Female            0
3   Vedant     87    Male            1
4   Parshv     90    Male            1
5   Mittal     83  Female            0
6  Archana     99  Female            0

In [60]:
df1
df1.drop('Male_Female',axis =1)

      Name  Marks  Gender  Half marks
0  Priyang     98    Male        49.0
1   Aadhya     89  Female        44.5
2   Krisha     99  Female        49.5
3   Vedant     87    Male        43.5
4   Parshv     90    Male        45.0
5   Mittal     83  Female        41.5
6  Archana     99  Female        49.5

In [64]:
df1.drop(['Male_Female','Half marks'], axis =1, inplace=True)
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [61]:
df1.columns

Index(['Name', 'Marks', 'Gender', 'Male_Female', 'Half marks'], dtype='str')

In [62]:
df1.index

RangeIndex(start=0, stop=7, step=1)

In [65]:
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [70]:
df1.sort_values(by=['Marks', 'Gender'],ascending = False)

      Name  Marks  Gender
2   Krisha     99  Female
6  Archana     99  Female
0  Priyang     98    Male
4   Parshv     90    Male
1   Aadhya     89  Female
3   Vedant     87    Male
5   Mittal     83  Female

In [71]:
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [80]:
df1[df1['Gender']=='Female'][['Name','Marks']]

      Name  Marks
1   Aadhya     89
2   Krisha     99
5   Mittal     83
6  Archana     99

In [81]:
df1[df1['Gender'].isin(['Female'])][['Name','Marks']]

      Name  Marks
1   Aadhya     89
2   Krisha     99
5   Mittal     83
6  Archana     99